# Visualize Data

In order to understand the dataset and what the files contain

In [6]:
import os
import pandas as pd
import numpy as np

In [7]:
# Read pickled df
df = pd.read_pickle("merged_df.pkl")
df.head()

,RNA-path,id,meth-path,mirna-path,project,OTHER_PATIENT_ID,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TISSUE_SITE,TUMOR_TYPE
0,/Users/couci/UTokyo/Research/SyntheticCancerCl...,0004d251-3f70-4395-b175-c94c2f5b1b81,/Users/couci/UTokyo/Research/SyntheticCancerCl...,/Users/couci/UTokyo/Research/SyntheticCancerCl...,TCGA-LIHC,0004d251-3f70-4395-b175-c94c2f5b1b81,Hepatobiliary Cancer,Hepatocellular Carcinoma,Liver,Hepatocellular Carcinoma
1,/Users/couci/UTokyo/Research/SyntheticCancerCl...,000d566c-96c7-4f1c-b36e-fa2222467983,/Users/couci/UTokyo/Research/SyntheticCancerCl...,/Users/couci/UTokyo/Research/SyntheticCancerCl...,TCGA-PRAD,000d566c-96c7-4f1c-b36e-fa2222467983,Prostate Cancer,Prostate Adenocarcinoma,Prostate,"Prostate Adenocarcinoma, Acinar Type"
2,/Users/couci/UTokyo/Research/SyntheticCancerCl...,001887aa-36d0-463f-8bca-dec7043b4f2e,/Users/couci/UTokyo/Research/SyntheticCancerCl...,/Users/couci/UTokyo/Research/SyntheticCancerCl...,TCGA-LIHC,001887aa-36d0-463f-8bca-dec7043b4f2e,Hepatobiliary Cancer,Hepatocellular Carcinoma,Liver,Hepatocellular Carcinoma
3,/Users/couci/UTokyo/Research/SyntheticCancerCl...,001944e5-af34-4061-9c09-bb9ea346f6fd,/Users/couci/UTokyo/Research/SyntheticCancerCl...,/Users/couci/UTokyo/Research/SyntheticCancerCl...,TCGA-BLCA,001944e5-af34-4061-9c09-bb9ea346f6fd,Bladder Cancer,Bladder Urothelial Carcinoma,Bladder,Muscle Invasive Urothelial Carcinoma (PT2 or A...
4,/Users/couci/UTokyo/Research/SyntheticCancerCl...,001ad307-4ad3-4f1d-b2fc-efc032871c7e,/Users/couci/UTokyo/Research/SyntheticCancerCl...,/Users/couci/UTokyo/Research/SyntheticCancerCl...,TCGA-LGG,001ad307-4ad3-4f1d-b2fc-efc032871c7e,Glioma,Oligoastrocytoma,CNS,Oligoastrocytoma

In [8]:
# get the path to the first RNA parquet file
first_rna_path = df.loc[df["RNA-path"].notna(), "RNA-path"].iloc[0]

rna_data = pd.read_parquet(first_rna_path)


print(rna_data.shape)
print(rna_data.columns)
rna_data.head()

(60660, 9)
Index(['gene_id', 'gene_name', 'gene_type', 'unstranded', 'stranded_first',
       'stranded_second', 'tpm_unstranded', 'fpkm_unstranded',
       'fpkm_uq_unstranded'],
      dtype='object')

,gene_id,gene_name,gene_type,unstranded,stranded_first,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
0,ENSG00000000003.15,TSPAN6,protein_coding,6088,3059,3029,136.4086,51.5682,79.6071
1,ENSG00000000005.6,TNMD,protein_coding,0,0,0,0.0000,0.0000,0.0000
2,ENSG00000000419.13,DPM1,protein_coding,558,265,293,46.9859,17.7626,27.4206
3,ENSG00000000457.14,SCYL3,protein_coding,390,430,435,5.7587,2.1770,3.3608
4,ENSG00000000460.17,C1orf112,protein_coding,133,317,307,2.2642,0.8560,1.3214

In [9]:
# Get path to the first DNA-methylation parquet file
first_dna_path = df.loc[df["meth-path"].notna(), "meth-path"].iloc[0]

dna_data = pd.read_parquet(first_dna_path)

print(dna_data.shape)
print(dna_data.columns)
dna_data.head()

(486427, 2)
Index(['site', 'beta'], dtype='object')

         site      beta
0  cg00000029       NaN
1  cg00000108  0.337825
2  cg00000109  0.870624
3  cg00000165       NaN
4  cg00000236  0.871063

In [10]:
# Get path to the first mirna parquet file
first_mirna_path = df.loc[df["mirna-path"].notna(), "mirna-path"].iloc[0]

mirna_data = pd.read_parquet(first_mirna_path)
print(mirna_data.shape)
print(mirna_data.columns)
mirna_data.head()

(1881, 4)
Index(['miRNA_ID', 'read_count', 'reads_per_million_miRNA_mapped',
       'cross-mapped'],
      dtype='object')

       miRNA_ID  read_count  reads_per_million_miRNA_mapped cross-mapped
0  hsa-let-7a-1       54754                     8837.171318            N
1  hsa-let-7a-2       54272                     8759.377612            Y
2  hsa-let-7a-3       55328                     8929.813615            N
3    hsa-let-7b       32570                     5256.724072            N
4    hsa-let-7c       21982                     3547.844905            Y